# INTRODUCTION {#ReCintro}

## What to expect in each chapter

This textbook is intended as *applied,* in that a primary goal is to help the scientist-practitioner-advocate use the statistic in a research problem and *write it up* for a program evaluation, dissertation, or journal article. In support of that goal, I try to provide *just enough* conceptual information so that the researcher can select the appropriate statistic (i.e., distinguishing between when ANOVA is appropriate and when regression is appropriate) and assign variables to their proper role (e.g., covariate, moderator, mediator).

This conceptual approach does include step-by-step *hand-calculations* (only we calculate them arithmetically in R) to provide a *visceral feeling* of what is happening within the statistical algorithm that may be invisible to the researcher.  Additionally, the conceptual review includes a review of the assumptions about the characteristics of the data and research design that are required for the statistic. Statistics can be daunting, so I have worked hard to establish a *workflow* through each analysis.When possible, I include a flowchart that is referenced frequently in each chapter. The flowchart is to help the researcher keep track of their place in the many steps and choices that accompany even the simplest of analyses.

As with many statistics texts, each chapter includes a *research vignette.* Somewhat unique to this resource is that the vignettes are selected from recently published articles. Each vignette is chosen with the intent to meet as many of the following criteria as possible:

* the statistic that is the focus of the chapter was properly used in the article,
* the author’s identity is from a group whose work has, historically been marginalized (e.g., BIPOC, LGBTQ+, or from a region of the globe where scholarship is often overlooked),
* the research has a justice, equity, inclusion, diversity, and social responsivity focus and will contribute positively to a social justice pedagogy, and 
* the data is available in a repository or there is sufficient information in the article to simulate the data for the chapter example(s) and practice problem(s).  

In each chapter we employ *R* packages that will efficiently calculate the statistic and the dashboard of metrics (e.g., effect sizes, confidence intervals) that are typically reported in psychological science.

## If You are New to R

In this section I will provide some orientation to using R in psychological research.  I don't intend this text to be "R from the ground up," but I will provide enough guidance that the individual can start working the problems.

I will also link to tutorials that help individuals get started in R.

### R Hygiene

Many problems in R can be resolved with good "R hygiene." I will review those practices here. I will also review the conventions I will try to consistently use throughout the text.

Everything in a folder

Although it is often considered good R etiquette to load all packages at the beginning of the script, this is not my practice.  Each chapter will include a script that lists all the packages used, but I will open each package as we use it. This will provide a greater sense of which packages are needed for what task.

## Maximizing Learning by Accessing all the Resources

In this section I will talk about the options for using and learning the materials.  Primarily these are:

1. Open a new document of R, copying the script over and running it in a fresh document.
2. Forking the entire suite of materials from GitHub and working directly in the original R markdown documents with the option to annotate the material directly.
3. Forking the materials to adopt and or adapt for teaching.
3. Listening to the accompanying lectures (I sound best when the speed is 1.75). I intend to record the lectures in Panopto which provides some closed captioning options.
4. Making use of the practice problems.
