<!DOCTYPE html>
<html lang="en" xml:lang="en">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Workflow for One-Way ANOVA | DRAFT: ReCentering Psych Stats</title>
  <meta name="description" content="This is an open-access, book-in-progress. My goal in offering it is to re-center the materials used in training statistics and research methods in graduate and post-graduate psychology programs." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Workflow for One-Way ANOVA | DRAFT: ReCentering Psych Stats" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is an open-access, book-in-progress. My goal in offering it is to re-center the materials used in training statistics and research methods in graduate and post-graduate psychology programs." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Workflow for One-Way ANOVA | DRAFT: ReCentering Psych Stats" />
  
  <meta name="twitter:description" content="This is an open-access, book-in-progress. My goal in offering it is to re-center the materials used in training statistics and research methods in graduate and post-graduate psychology programs." />
  

<meta name="author" content="Lynette H Bikos, PhD, ABPP" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="oneway.html"/>
<link rel="next" href="working-the-one-way-for-real.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-5488840-4', 'auto');
  ga('send', 'pageview');

</script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./"><strong>ReCentering Psych Stats</strong><br>by Lynette H Bikos, PhD, ABPP</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#copyright-with-open-access"><i class="fa fa-check"></i>Copyright with Open Access</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="ReCintro.html"><a href="ReCintro.html"><i class="fa fa-check"></i><b>1</b> INTRODUCTION</a><ul>
<li class="chapter" data-level="1.1" data-path="ReCintro.html"><a href="ReCintro.html#what-to-expect-in-each-chapter"><i class="fa fa-check"></i><b>1.1</b> What to expect in each chapter</a></li>
<li class="chapter" data-level="1.2" data-path="ReCintro.html"><a href="ReCintro.html#if-you-are-new-to-r"><i class="fa fa-check"></i><b>1.2</b> If You are New to R</a></li>
<li class="chapter" data-level="1.3" data-path="ReCintro.html"><a href="ReCintro.html#maximizing-learning-by-accessing-all-the-resources"><i class="fa fa-check"></i><b>1.3</b> Maximizing Learning by Accessing all the Resources</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="oneway.html"><a href="oneway.html"><i class="fa fa-check"></i><b>2</b> ONE-WAY ANOVA</a><ul>
<li class="chapter" data-level="2.1" data-path="oneway.html"><a href="oneway.html#navigating-this-lesson"><i class="fa fa-check"></i><b>2.1</b> Navigating this Lesson</a><ul>
<li class="chapter" data-level="2.1.1" data-path="oneway.html"><a href="oneway.html#learning-objectives"><i class="fa fa-check"></i><b>2.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="2.1.2" data-path="oneway.html"><a href="oneway.html#planning-for-practice"><i class="fa fa-check"></i><b>2.1.2</b> Planning for Practice</a></li>
<li class="chapter" data-level="2.1.3" data-path="oneway.html"><a href="oneway.html#readings-resources"><i class="fa fa-check"></i><b>2.1.3</b> Readings &amp; Resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="workflow-for-one-way-anova.html"><a href="workflow-for-one-way-anova.html"><i class="fa fa-check"></i>Workflow for One-Way ANOVA</a><ul>
<li class="chapter" data-level="2.2" data-path="workflow-for-one-way-anova.html"><a href="workflow-for-one-way-anova.html#motivational-example"><i class="fa fa-check"></i><b>2.2</b> Motivational Example</a><ul>
<li class="chapter" data-level="2.2.1" data-path="workflow-for-one-way-anova.html"><a href="workflow-for-one-way-anova.html#exploring-data"><i class="fa fa-check"></i><b>2.2.1</b> 2. Exploring Data</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="workflow-for-one-way-anova.html"><a href="workflow-for-one-way-anova.html#understanding-anova"><i class="fa fa-check"></i><b>2.3</b> Understanding ANOVA</a><ul>
<li class="chapter" data-level="2.3.1" data-path="workflow-for-one-way-anova.html"><a href="workflow-for-one-way-anova.html#sums-of-squares-for-the-model"><i class="fa fa-check"></i><b>2.3.1</b> Sums of Squares for the Model</a></li>
<li class="chapter" data-level="2.3.2" data-path="workflow-for-one-way-anova.html"><a href="workflow-for-one-way-anova.html#sums-of-squares-residual-or-within"><i class="fa fa-check"></i><b>2.3.2</b> Sums of Squares Residual (or within)</a></li>
<li class="chapter" data-level="2.3.3" data-path="workflow-for-one-way-anova.html"><a href="workflow-for-one-way-anova.html#relationship-between-ss_t-ss_m-and-ss_r.-in-case-its-not-clear"><i class="fa fa-check"></i><b>2.3.3</b> Relationship between <span class="math inline">\(SS_T\)</span>, <span class="math inline">\(SS_M\)</span>, and <span class="math inline">\(SS_R\)</span>. In case it’s not clear:</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="workflow-for-one-way-anova.html"><a href="workflow-for-one-way-anova.html#mean-squares-model-residual"><i class="fa fa-check"></i><b>2.4</b> Mean Squares Model &amp; Residual</a></li>
<li class="chapter" data-level="2.5" data-path="workflow-for-one-way-anova.html"><a href="workflow-for-one-way-anova.html#all-thats-left-is-the-f---ratio"><i class="fa fa-check"></i><b>2.5</b> All that’s left is the <em>F</em> - ratio</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="working-the-one-way-for-real.html"><a href="working-the-one-way-for-real.html"><i class="fa fa-check"></i>woRking the one-way for Real</a><ul>
<li class="chapter" data-level="2.6" data-path="working-the-one-way-for-real.html"><a href="working-the-one-way-for-real.html#evaluating-the-statistical-assumptions"><i class="fa fa-check"></i><b>2.6</b> Evaluating the statistical assumptions</a><ul>
<li class="chapter" data-level="2.6.1" data-path="working-the-one-way-for-real.html"><a href="working-the-one-way-for-real.html#is-it-normally-distributed"><i class="fa fa-check"></i><b>2.6.1</b> Is it normally distributed?</a></li>
<li class="chapter" data-level="2.6.2" data-path="working-the-one-way-for-real.html"><a href="working-the-one-way-for-real.html#evaluating-the-homogeneity-of-variance-assumption-with-levenes-test"><i class="fa fa-check"></i><b>2.6.2</b> Evaluating the Homogeneity of Variance Assumption with Levene’s Test</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="working-the-one-way-for-real.html"><a href="working-the-one-way-for-real.html#compute-the-omnibus-anova"><i class="fa fa-check"></i><b>2.7</b> Compute the omnibus ANOVA</a><ul>
<li class="chapter" data-level="2.7.1" data-path="working-the-one-way-for-real.html"><a href="working-the-one-way-for-real.html#effect-size-for-the-one-way-anova"><i class="fa fa-check"></i><b>2.7.1</b> Effect size for the one-way ANOVA</a></li>
<li class="chapter" data-level="2.7.2" data-path="working-the-one-way-for-real.html"><a href="working-the-one-way-for-real.html#follow-up-to-the-omnibus"><i class="fa fa-check"></i><b>2.7.2</b> Follow-up to the omnibus</a></li>
<li class="chapter" data-level="2.7.3" data-path="working-the-one-way-for-real.html"><a href="working-the-one-way-for-real.html#which-set-of-follow-up-tests-do-we-use"><i class="fa fa-check"></i><b>2.7.3</b> Which set of follow-up tests do we use?</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="working-the-one-way-for-real.html"><a href="working-the-one-way-for-real.html#but-what-if-we-violated-the-homogeneity-of-variance-test"><i class="fa fa-check"></i><b>2.8</b> But what if we violated the Homogeneity of Variance test?</a></li>
<li class="chapter" data-level="2.9" data-path="working-the-one-way-for-real.html"><a href="working-the-one-way-for-real.html#power-analysis"><i class="fa fa-check"></i><b>2.9</b> Power Analysis</a></li>
<li class="chapter" data-level="2.10" data-path="working-the-one-way-for-real.html"><a href="working-the-one-way-for-real.html#apa-style-results"><i class="fa fa-check"></i><b>2.10</b> APA Style Results</a></li>
<li class="chapter" data-level="2.11" data-path="working-the-one-way-for-real.html"><a href="working-the-one-way-for-real.html#bonus-reel"><i class="fa fa-check"></i><b>2.11</b> Bonus Reel:</a></li>
<li class="chapter" data-level="2.12" data-path="working-the-one-way-for-real.html"><a href="working-the-one-way-for-real.html#references"><i class="fa fa-check"></i><b>2.12</b> References</a></li>
</ul></li>
<li class="divider"></li>
#<li><a href="https:link" target="_blank">Open access book-in-progress</br>
<li><a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a></li>
  <li><a href="https://bookdown.org" target="_blank">Built with Bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">DRAFT: ReCentering Psych Stats</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="workflow-for-one-way-anova" class="section level1 unnumbered">
<h1>Workflow for One-Way ANOVA</h1>
<p>The following is a proposed workflow for conducting a one-way ANOVA. For a separate document <a href="images/OnewayWrkFlw.png">See screenshot</a></p>
<div class="figure">
<img src="images/OnewayWrkFlw.jpg" alt="" />
<p class="caption">An image of a workflow for the one-way ANOVA</p>
</div>
<ol style="list-style-type: decimal">
<li>Prepare (upload) data.</li>
<li>Explore data
<ul>
<li>graphs</li>
<li>descriptive statistics</li>
</ul></li>
<li>Checking distributional assumptions
<ul>
<li>assessing normality via skew, kurtosis, Shapiro Wilks</li>
<li>checking for violation of homogeneity of variance assumption with Levene’s test; if we violate this we can use Welch’s omnibus ANOVA</li>
</ul></li>
<li>Compute the omnibus ANOVA (remember to use Welch’s if Levene’s <em>p</em> &lt; .05)</li>
<li>Compute post hoc comparisons, planned contrasts, or polynomial trends</li>
<li>Managing Type I error</li>
<li>Sample size/power analysis (which you should think about first – but in the context of teaching ANOVA, it’s more pedagogically sensible, here)</li>
</ol>
<div id="motivational-example" class="section level2">
<h2><span class="header-section-number">2.2</span> Motivational Example</h2>
<p>The <em>exceptionalizing racial stereotype</em> is microaggression framed as interpersonally complimentary, but perpetuates negative stereotypical views of a racial/ethnic group. We are using data that is <em>simulated</em> from a random clinical trial (RCT) conducted by Tran and Lee <span class="citation">(<a href="#ref-tran_you_2014" role="doc-biblioref">2014</a>)</span>.</p>
<p>The one-way ANOVA examples we are simulating represent the post-only design which investigated three levels of the exceptionalizing stereotype in a sample of Asian American participants. This experimental design involved a confederate (posing as a peer) whose parting comment fell into the low racial loading, high racial loading, or control conditions.</p>
<div class="figure">
<img src="PostOnly.jpg" id="id" class="class" width="1000" height="500" alt="" />
<p class="caption">Opening image</p>
</div>
<p>Tran and Lee <span class="citation">(<a href="#ref-tran_you_2014" role="doc-biblioref">2014</a>)</span> reported results from two ANOVAs and 4 ANCOVAs, using a pre-test as a covariate. A preprint of the article is available <a href="https://pdfs.semanticscholar.org/4146/b528961c041de317c6a4c699f12fc5a4bc22.pdf?_ga=2.179078439.2028716028.1610939782-1660125104.1610939782">here</a>.</p>
<ul>
<li><strong>Accurate</strong> is the DV we will be exploring in class. Participants rated how <em>accurate</em> they believed their partner’s impression of them was (0 = <em>very inaccurate</em>, 3 = <em>very accurate</em>).</li>
<li><strong>moreTalk</strong> is the DV assigned for homework. Participants rated how much longer they would continue the interaction with their partner compared to their interactions in general (-2 = <em>much less than average</em>, 0 = <em>average</em>, 2 = <em>much more than average</em>)</li>
</ul>
<p>###1. Preparing and Uploading Data</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="workflow-for-one-way-anova.html#cb1-1"></a><span class="co">#for a .csv file</span></span>
<span id="cb1-2"><a href="workflow-for-one-way-anova.html#cb1-2"></a>accSIM30 &lt;-<span class="st"> </span><span class="kw">read.csv</span> (<span class="st">&quot;Acc_sim30_df.csv&quot;</span>, <span class="dt">head =</span> <span class="ot">TRUE</span>, <span class="dt">sep =</span> <span class="st">&quot;,&quot;</span>)</span>
<span id="cb1-3"><a href="workflow-for-one-way-anova.html#cb1-3"></a></span>
<span id="cb1-4"><a href="workflow-for-one-way-anova.html#cb1-4"></a><span class="co"># head=TRUE yields column headings;</span></span>
<span id="cb1-5"><a href="workflow-for-one-way-anova.html#cb1-5"></a><span class="co"># sep = &quot;,&quot; tells R that we are using a .csv file (comma separated values)</span></span></code></pre></div>
<p>Examining data is super useful in determining which ANOVA to use.</p>
<ul>
<li>look at it by clicking on it</li>
<li>examine its structure with the <em>str()</em> function</li>
</ul>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="workflow-for-one-way-anova.html#cb2-1"></a><span class="kw">str</span>(accSIM30)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    90 obs. of  3 variables:
##  $ ID      : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ COND    : chr  &quot;High&quot; &quot;High&quot; &quot;High&quot; &quot;High&quot; ...
##  $ Accurate: num  1.86 1.75 2.59 1.38 2.03 ...</code></pre>
<p>If we look at this super simple dataset, we see that we see that</p>
<ul>
<li>COND is a grouping variable) with 3 levels (high, low, control)
<ul>
<li>it is presently in “chr” (character) format, it needs to be a factor</li>
</ul></li>
<li>Accurate is a continuous variable
<ul>
<li>it is presently in “num” (numerical) format, which is fine</li>
</ul></li>
</ul>
<p>There are many ways to convert variables to factors; here’s one of the simplest.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="workflow-for-one-way-anova.html#cb4-1"></a>accSIM30<span class="op">$</span>COND &lt;-<span class="st"> </span><span class="kw">factor</span>(accSIM30<span class="op">$</span>COND)</span></code></pre></div>
<p>Let’s recheck the structure</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="workflow-for-one-way-anova.html#cb5-1"></a><span class="kw">str</span>(accSIM30)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    90 obs. of  3 variables:
##  $ ID      : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ COND    : Factor w/ 3 levels &quot;Control&quot;,&quot;High&quot;,..: 2 2 2 2 2 2 2 2 2 2 ...
##  $ Accurate: num  1.86 1.75 2.59 1.38 2.03 ...</code></pre>
<p>R orders factors alphabetically. This means, analysis will assume that “Control” (C) is the lowest condition, then “High,” then “Low.” Since these have theoretically ordered values, we want them ordered “Control,” “Low,” “High.”</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="workflow-for-one-way-anova.html#cb7-1"></a>accSIM30<span class="op">$</span>COND &lt;-<span class="st"> </span><span class="kw">factor</span>(accSIM30<span class="op">$</span>COND, <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">&quot;Control&quot;</span>, <span class="st">&quot;Low&quot;</span>, <span class="st">&quot;High&quot;</span>))</span></code></pre></div>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="workflow-for-one-way-anova.html#cb8-1"></a><span class="kw">str</span>(accSIM30)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    90 obs. of  3 variables:
##  $ ID      : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ COND    : Factor w/ 3 levels &quot;Control&quot;,&quot;Low&quot;,..: 3 3 3 3 3 3 3 3 3 3 ...
##  $ Accurate: num  1.86 1.75 2.59 1.38 2.03 ...</code></pre>
<p>R will always guess the variable format when importing a .csv and, in this case, it will always guess incorrectly. We need to write our script so that we are always checking and updating the structure of variables.</p>
<div id="exploring-data" class="section level3">
<h3><span class="header-section-number">2.2.1</span> 2. Exploring Data</h3>
<p>If we just want to grab a quick mean, and then a standard deviation</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="workflow-for-one-way-anova.html#cb10-1"></a><span class="kw">aggregate</span> (Accurate <span class="op">~</span><span class="st"> </span>COND, accSIM30, mean)</span></code></pre></div>
<pre><code>##      COND Accurate
## 1 Control 1.876882
## 2     Low 2.046506
## 3    High 1.473640</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="workflow-for-one-way-anova.html#cb12-1"></a><span class="kw">aggregate</span> (Accurate <span class="op">~</span><span class="st"> </span>COND, accSIM30, sd)</span></code></pre></div>
<pre><code>##      COND  Accurate
## 1 Control 0.4791969
## 2     Low 0.5725299
## 3    High 0.7653157</code></pre>
<p>Before looking at the graphs, we can see that racially loaded <em>high</em> condition has the lowest accuracy score and the largest variability. Let’s take a look at the graphs to “see” this.</p>
<div id="first-with-graphs." class="section level4">
<h4><span class="header-section-number">2.2.1.1</span> First with graphs.</h4>
<p>First, a line graph. This plots the means with error bars (95% confidence intervals) around the mean. We can think, “How confident are we that the mean is this particular value?”</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="workflow-for-one-way-anova.html#cb14-1"></a><span class="kw">library</span>(gplots)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;gplots&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     lowess</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="workflow-for-one-way-anova.html#cb17-1"></a><span class="kw">plotmeans</span> (<span class="dt">formula =</span> Accurate <span class="op">~</span><span class="st"> </span>COND, <span class="co">#plots DV by IV</span></span>
<span id="cb17-2"><a href="workflow-for-one-way-anova.html#cb17-2"></a>           <span class="dt">data =</span> accSIM30, <span class="co">#identifies the data frame</span></span>
<span id="cb17-3"><a href="workflow-for-one-way-anova.html#cb17-3"></a>           <span class="dt">xlab =</span> <span class="st">&quot;Racial Loading Condition&quot;</span>, <span class="co">#let&#39;s us specify a label for the x-axis</span></span>
<span id="cb17-4"><a href="workflow-for-one-way-anova.html#cb17-4"></a>           <span class="dt">ylab =</span> <span class="st">&quot;Accuracy of Confederate&#39;s Impression&quot;</span>, <span class="co">#let&#39;s us specify a label for the y-axis</span></span>
<span id="cb17-5"><a href="workflow-for-one-way-anova.html#cb17-5"></a>           <span class="dt">n.label =</span> <span class="ot">TRUE</span>  <span class="co">#we can even specify the sample size for each level of the group</span></span>
<span id="cb17-6"><a href="workflow-for-one-way-anova.html#cb17-6"></a>           )</span></code></pre></div>
<p><img src="ReCenterPsychStats_files/figure-html/linegraph-1.svg" width="672" /></p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="workflow-for-one-way-anova.html#cb18-1"></a><span class="co">#you can totally write this in one row</span></span>
<span id="cb18-2"><a href="workflow-for-one-way-anova.html#cb18-2"></a><span class="co">#plotmeans (formula = Accurate ~ COND, data = accSIM30, xlab = &quot;Racial Loading Condition&quot;, ylab = &quot;Accuracy of Confederate&#39;s Impression&quot;, n.label = TRUE)</span></span></code></pre></div>
<p>Viewed another way, we can create a boxplot. In the boxplot, the center value is the median. The box spans the <em>interquartile range</em>, ranging from the 25th to the 75th percentile. The whiskers theoretically include the minimum and maximum. Theoretically they cover 1.5 times the interquartile range and represent outliers with dots.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="workflow-for-one-way-anova.html#cb19-1"></a><span class="kw">boxplot2</span> (Accurate <span class="op">~</span><span class="st"> </span>COND, <span class="dt">data =</span> accSIM30, <span class="dt">xlab =</span> <span class="st">&quot;Racial Loading Condition&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Accuracy of Confederate&#39;s Impression&quot;</span>, <span class="dt">n.label =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<p><img src="ReCenterPsychStats_files/figure-html/boxplot-1.svg" width="672" /></p>
<p>From both the boxplot and the linegraph with error bars, we can see that as the the contol and low racial loading conditions have a comparable level of the accuracy variable (i.e., the degree to which the confederate’s impression is accurate). Participants in the high racial loading condition reported a lower level of accuracy).</p>
</div>
</div>
</div>
<div id="understanding-anova" class="section level2">
<h2><span class="header-section-number">2.3</span> Understanding ANOVA</h2>
<p>ANOVA was developed by Sir Ronald Fisher in the early 20th century. The name is a bit of a misnomer – rather than analyzing <em>variances</em>, we are investigating differences in <em>means</em> (but the formula does take variances into consideration…stay tuned).</p>
<p>ANOVA falls squarely within the tradition of <strong>null hypothesis significance testing</strong> (NHST). As such, a formal ANOVA begins with statements of the null and alternate hypotheses. <em>Note. Tran and Lee <span class="citation">(<a href="#ref-tran_you_2014" role="doc-biblioref">2014</a>)</span> do not list such.</em></p>
<p>In our example, we would hypothesize that the population means (i.e., Asian or Asian American individuals in the U.S.) are equal:</p>
<p><span class="math display">\[H_{O}:  \mu _{1} = \mu _{2} = \mu _{3}\]</span></p>
<p>There are an number of ways that the <span class="math inline">\(H_{O}\)</span> could be false. Here are a few:</p>
<p><span class="math display">\[H_{a1}:  \mu _{1} \neq \mu _{2} \neq \mu _{3}\]</span>
<span class="math display">\[H_{a2}:  \mu _{1} =  \mu _{2} &gt; \mu _{3}\]</span></p>
<p><span class="math display">\[H_{a3}:  \mu _{1} &gt;  \mu _{2} &gt; \mu _{3}\]</span>
The bottom line is that somewhere between the three levels of the grouping factor, the means are statistically significantly different from each other.</p>
<p>In evaluating the differences between means, one-way ANOVA compares:</p>
<ul>
<li>systematic variance to unsystematic variance</li>
<li>explained to unexplained variation</li>
<li>experimental effect to the individual differences</li>
<li>model variance to residual variance</li>
<li>between group variance to within group variance
(in an experiment)</li>
</ul>
<p>The ratio of these variances is the <strong>F-ratio</strong>.</p>
<p>Navarro <span class="citation">(<a href="#ref-navarro_book_2020" role="doc-biblioref">2020</a>)</span> offers a useful figure to compare between- and within-group variation.</p>
<p><img src="BetweenWithin.jpg" id="id" class="class" width="1000" height="400" alt="Image comparing between- and within-subjects variation. Source is the Navarro 2020 text" />
### Sums of Squares Total</p>
<p><span class="math display">\[SS_{T}= \sum (x_{i}-\bar{x}_{grand})^{2}\]</span>
<span class="math display">\[SS_{T}= SS_{M} + SS_{R}\]</span>
<span class="math display">\[SS_{T}= SS_{B} + SS_{W}\]</span>
<span class="math display">\[SS_{T}= s_{grand}^{2}(n-1)\]</span>
Let’s take a moment to <em>hand-calculate</em> <span class="math inline">\(SS_{T}\)</span> (but in R).</p>
<p>Our grand (i.e., overall) mean is</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="workflow-for-one-way-anova.html#cb20-1"></a><span class="kw">mean</span>(accSIM30<span class="op">$</span>Accurate)</span></code></pre></div>
<pre><code>## [1] 1.799009</code></pre>
<p>Subtracting the grand mean from each Accurate score yields a mean difference.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="workflow-for-one-way-anova.html#cb22-1"></a><span class="kw">library</span>(tidyverse)</span></code></pre></div>
<pre><code>## -- Attaching packages --------------------------------------- tidyverse 1.3.0 --</code></pre>
<pre><code>## v ggplot2 3.3.3     v purrr   0.3.4
## v tibble  3.0.4     v dplyr   1.0.2
## v tidyr   1.1.2     v stringr 1.4.0
## v readr   1.4.0     v forcats 0.5.0</code></pre>
<pre><code>## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="workflow-for-one-way-anova.html#cb26-1"></a>accSIM30 &lt;-<span class="st"> </span>accSIM30 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb26-2"><a href="workflow-for-one-way-anova.html#cb26-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">m_dev =</span> Accurate<span class="op">-</span><span class="kw">mean</span>(Accurate))</span></code></pre></div>
<p>Pop quiz: What’s the sum of our new <em>m_dev</em> variable?</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="workflow-for-one-way-anova.html#cb27-1"></a><span class="kw">mean</span>(accSIM30<span class="op">$</span>m_dev)</span></code></pre></div>
<pre><code>## [1] -5.421372e-17</code></pre>
<p>If we square those mean deviations:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="workflow-for-one-way-anova.html#cb29-1"></a>accSIM30 &lt;-<span class="st"> </span>accSIM30 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb29-2"><a href="workflow-for-one-way-anova.html#cb29-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">m_devSQ =</span> m_dev<span class="op">^</span><span class="dv">2</span>)</span></code></pre></div>
<p>If we sum the squared mean deviations:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="workflow-for-one-way-anova.html#cb30-1"></a><span class="kw">sum</span>(accSIM30<span class="op">$</span>m_devSQ)</span></code></pre></div>
<pre><code>## [1] 38.34623</code></pre>
<p>This value, the sum of squared deviations around the grand mean, is our <span class="math inline">\(SS_T\)</span>; the associated <em>degrees of freedom</em> is <span class="math inline">\(N\)</span> - 1.<br />
In one-way ANOVA, we divide <span class="math inline">\(SS_T\)</span> into <strong>model/between sums of squares</strong> and <strong>residual/within sums of squares</strong>.</p>
<p>The <em>model</em> generally represents the notion that the means are different than each other. We want the variation between our means to be greater than the variation within each of the groups from which our means are calculated.</p>
<div id="sums-of-squares-for-the-model" class="section level3">
<h3><span class="header-section-number">2.3.1</span> Sums of Squares for the Model</h3>
<p><span class="math display">\[SS_{M}= \sum n_{k}(\bar{x}_{k}-\bar{x}_{grand})^{2}\]</span></p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="workflow-for-one-way-anova.html#cb32-1"></a><span class="kw">mean</span>(accSIM30<span class="op">$</span>Accurate)</span></code></pre></div>
<pre><code>## [1] 1.799009</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="workflow-for-one-way-anova.html#cb34-1"></a><span class="kw">aggregate</span> (Accurate <span class="op">~</span><span class="st"> </span>COND, accSIM30, mean)</span></code></pre></div>
<pre><code>##      COND Accurate
## 1 Control 1.876882
## 2     Low 2.046506
## 3    High 1.473640</code></pre>
<p>This formula occurs in three chunks, representing the control, low, and high racial loading conditions. In each of the chunks we have the <span class="math inline">\(n\)</span>, group mean, and grand mean.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="workflow-for-one-way-anova.html#cb36-1"></a><span class="dv">30</span><span class="op">*</span>(<span class="fl">1.876</span> <span class="op">-</span><span class="st"> </span><span class="fl">1.799</span>)<span class="op">^</span><span class="dv">2</span> <span class="op">+</span><span class="st"> </span><span class="dv">30</span><span class="op">*</span>(<span class="fl">2.046</span> <span class="op">-</span><span class="st"> </span><span class="fl">1.799</span>)<span class="op">^</span><span class="dv">2</span> <span class="op">+</span><span class="st"> </span><span class="dv">30</span><span class="op">*</span>(<span class="fl">1.474</span> <span class="op">-</span><span class="st"> </span><span class="fl">1.799</span>)<span class="op">^</span><span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] 5.17689</code></pre>
<p>This value, <span class="math inline">\(SS_M\)</span> is the value accounted for by the model – the proportion of variance accounted for by the grouping variable/factor, COND.</p>
</div>
<div id="sums-of-squares-residual-or-within" class="section level3">
<h3><span class="header-section-number">2.3.2</span> Sums of Squares Residual (or within)</h3>
<p><span class="math display">\[SS_{R}= \sum(x_{ik}-\bar{x}_{k})^{^{2}}\]</span>
Here’s another configuration of the same:</p>
<p><span class="math display">\[SS_{R}= s_{group1}^{2}(n-1) + s_{group2}^{2}(n-1) + s_{group3}^{2}(n-1))\]</span>
Again, the formula is in three chunks – but this time the calculations are <em>within-group</em>. We need the variance (the standard deviation squared) for the calculation.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="workflow-for-one-way-anova.html#cb38-1"></a><span class="kw">aggregate</span> (Accurate <span class="op">~</span><span class="st"> </span>COND, accSIM30, sd)</span></code></pre></div>
<pre><code>##      COND  Accurate
## 1 Control 0.4791969
## 2     Low 0.5725299
## 3    High 0.7653157</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="workflow-for-one-way-anova.html#cb40-1"></a><span class="co">#just showing you that the variance (next) is the standard deviation, squared</span></span>
<span id="cb40-2"><a href="workflow-for-one-way-anova.html#cb40-2"></a><span class="fl">.4791969</span><span class="op">^</span><span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] 0.2296297</code></pre>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="workflow-for-one-way-anova.html#cb42-1"></a><span class="kw">aggregate</span> (Accurate <span class="op">~</span><span class="st"> </span>COND, accSIM30, var)</span></code></pre></div>
<pre><code>##      COND  Accurate
## 1 Control 0.2296297
## 2     Low 0.3277905
## 3    High 0.5857082</code></pre>
<p>Calculating <span class="math inline">\(SS_R\)</span></p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="workflow-for-one-way-anova.html#cb44-1"></a><span class="fl">.2296</span><span class="op">*</span>(<span class="dv">30-1</span>) <span class="op">+</span><span class="st"> </span><span class="fl">.3278</span><span class="op">*</span>(<span class="dv">30-1</span>) <span class="op">+</span><span class="st"> </span><span class="fl">.5857</span><span class="op">*</span>(<span class="dv">30-1</span>)</span></code></pre></div>
<pre><code>## [1] 33.1499</code></pre>
<p>The value for our <span class="math inline">\(SS_R\)</span> is 33.15. It’s degrees of freedom is <span class="math inline">\(N - k\)</span>, meaning the total <span class="math inline">\(N\)</span> minus the number of groups: 90 - 3 = 87.</p>
</div>
<div id="relationship-between-ss_t-ss_m-and-ss_r.-in-case-its-not-clear" class="section level3">
<h3><span class="header-section-number">2.3.3</span> Relationship between <span class="math inline">\(SS_T\)</span>, <span class="math inline">\(SS_M\)</span>, and <span class="math inline">\(SS_R\)</span>. In case it’s not clear:</h3>
<p><span class="math inline">\(SS_T = SS_M + SS_R\)</span></p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="workflow-for-one-way-anova.html#cb46-1"></a><span class="fl">33.15</span> <span class="op">+</span><span class="st"> </span><span class="fl">5.18</span></span></code></pre></div>
<pre><code>## [1] 38.33</code></pre>
</div>
</div>
<div id="mean-squares-model-residual" class="section level2">
<h2><span class="header-section-number">2.4</span> Mean Squares Model &amp; Residual</h2>
<p>Now that we have the Sums of Squares, we can calculate the mean squares (we need these for our <span class="math inline">\(F\)</span> statistic).</p>
<p><span class="math display">\[MS_M = \frac{SS_{M}}{df^{_{M}}}\]</span></p>
<p>In our case, <span class="math inline">\(MS_M=\)</span></p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="workflow-for-one-way-anova.html#cb48-1"></a><span class="co"># mean squares for the model</span></span>
<span id="cb48-2"><a href="workflow-for-one-way-anova.html#cb48-2"></a><span class="fl">5.17689</span><span class="op">/</span><span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] 2.588445</code></pre>
<p>And <span class="math inline">\(MS_R=\)</span>
<span class="math display">\[MS_R = \frac{SS_{R}}{df^{_{R}}}\]</span>
Recall, df for the resitual is N - k
(in our case that’s 90 - 3)</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="workflow-for-one-way-anova.html#cb50-1"></a><span class="co"># mean squares for the residual</span></span>
<span id="cb50-2"><a href="workflow-for-one-way-anova.html#cb50-2"></a><span class="fl">33.1499</span> <span class="op">/</span><span class="st"> </span><span class="dv">87</span></span></code></pre></div>
<pre><code>## [1] 0.3810333</code></pre>
</div>
<div id="all-thats-left-is-the-f---ratio" class="section level2">
<h2><span class="header-section-number">2.5</span> All that’s left is the <em>F</em> - ratio</h2>
<p><span class="math display">\[F = \frac{MS_{M}}{MS_{R}}\]</span></p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="workflow-for-one-way-anova.html#cb52-1"></a><span class="fl">2.588445</span> <span class="op">/</span><span class="st"> </span><span class="fl">0.3810333</span></span></code></pre></div>
<pre><code>## [1] 6.793225</code></pre>
<p>These last few calculations are actually less complicated than this presentation makes them seem. We should play <strong>Source Table Games</strong>!</p>
<p>Knowing only two of the values, challenge yourself to complete the rest of the table.</p>
<div class="figure">
<img src="SourceTableGames.jpg" id="id" class="class" width="1000" height="800" alt="" />
<p class="caption">Opening image</p>
</div>
<p>To determine whether or not it is statistically significant, we can check an table of critical values for the <em>F</em> test. Here’s a handy one:<br />
<a href="https://www.statology.org/how-to-read-the-f-distribution-table/" class="uri">https://www.statology.org/how-to-read-the-f-distribution-table/</a></p>
<p>Our example has 2 (numerator) and 87 (denominator) degrees of freedom. Rolling down to the table where <span class="math inline">\(\alpha = .05\)</span>, we can see that any <span class="math inline">\(F\)</span> value &gt; 3.11 (a value somewhere between 3.07 and 3.15) will be statistically significant. Our <span class="math inline">\(F\)</span> = 6.79, so we have clearly exceeded the threshhold. This is our <em>omnibus F</em>. We know there is at least 1 statistically significant difference between our control, low, and high racially loaded conditions.</p>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-navarro_book_2020">
<p>Navarro, D. (2020). <em>Book: Learning Statistics with R - A tutorial for Psychology Students and other Beginners</em>. Open Education Resource (OER) LibreTexts Project. <a href="https://stats.libretexts.org/Bookshelves/Applied_Statistics/Book%3A_Learning_Statistics_with_R_-_A_tutorial_for_Psychology_Students_and_other_Beginners_(Navarro)">https://stats.libretexts.org/Bookshelves/Applied_Statistics/Book%3A_Learning_Statistics_with_R_-_A_tutorial_for_Psychology_Students_and_other_Beginners_(Navarro)</a></p>
</div>
<div id="ref-tran_you_2014">
<p>Tran, A. G. T. T., &amp; Lee, R. M. (2014). You speak English well! Asian Americans’ reactions to an exceptionalizing stereotype. <em>Journal of Counseling Psychology</em>, <em>61</em>(3), 484–490. <a href="https://doi.org/10.1037/cou0000034">https://doi.org/10.1037/cou0000034</a></p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="oneway.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="working-the-one-way-for-real.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/ontheline/otl-bookdown/blob/master/02-OnewayANOVA.Rmd",
"text": null
},
"download": ["ReCenterPsychStats.pdf"],
"toc": {
"collapse": "section",
"scroll_highlight": true
},
"search": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
