<!DOCTYPE html>
<html lang="en" xml:lang="en">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Working the One-Way ANOVA in R | DRAFT: ReCentering Psych Stats</title>
  <meta name="description" content="This is an open-access, book-in-progress. My goal in offering it is to re-center the materials used in training statistics and research methods in graduate and post-graduate psychology programs." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Working the One-Way ANOVA in R | DRAFT: ReCentering Psych Stats" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is an open-access, book-in-progress. My goal in offering it is to re-center the materials used in training statistics and research methods in graduate and post-graduate psychology programs." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Working the One-Way ANOVA in R | DRAFT: ReCentering Psych Stats" />
  
  <meta name="twitter:description" content="This is an open-access, book-in-progress. My goal in offering it is to re-center the materials used in training statistics and research methods in graduate and post-graduate psychology programs." />
  

<meta name="author" content="Lynette H Bikos, PhD, ABPP" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="oneway.html"/>

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-5488840-4', 'auto');
  ga('send', 'pageview');

</script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./"><strong>ReCentering Psych Stats</strong><br>by Lynette H Bikos, PhD, ABPP</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#copyright-with-open-access"><i class="fa fa-check"></i>Copyright with Open Access</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="ReCintro.html"><a href="ReCintro.html"><i class="fa fa-check"></i><b>1</b> INTRODUCTION</a><ul>
<li class="chapter" data-level="1.1" data-path="ReCintro.html"><a href="ReCintro.html#what-to-expect-in-each-chapter"><i class="fa fa-check"></i><b>1.1</b> What to expect in each chapter</a></li>
<li class="chapter" data-level="1.2" data-path="ReCintro.html"><a href="ReCintro.html#if-you-are-new-to-r"><i class="fa fa-check"></i><b>1.2</b> If You are New to R</a></li>
<li class="chapter" data-level="1.3" data-path="ReCintro.html"><a href="ReCintro.html#r-hygiene"><i class="fa fa-check"></i><b>1.3</b> R Hygiene</a></li>
<li class="chapter" data-level="1.4" data-path="ReCintro.html"><a href="ReCintro.html#maximizing-learning-by-accessing-all-the-resources"><i class="fa fa-check"></i><b>1.4</b> Maximizing Learning by Accessing all the Resources</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="oneway.html"><a href="oneway.html"><i class="fa fa-check"></i><b>2</b> ONE-WAY ANOVA</a><ul>
<li class="chapter" data-level="2.1" data-path="oneway.html"><a href="oneway.html#navigating-this-lesson"><i class="fa fa-check"></i><b>2.1</b> Navigating this Lesson</a><ul>
<li class="chapter" data-level="2.1.1" data-path="oneway.html"><a href="oneway.html#learning-objectives"><i class="fa fa-check"></i><b>2.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="2.1.2" data-path="oneway.html"><a href="oneway.html#planning-for-practice"><i class="fa fa-check"></i><b>2.1.2</b> Planning for Practice</a></li>
<li class="chapter" data-level="2.1.3" data-path="oneway.html"><a href="oneway.html#readings-resources"><i class="fa fa-check"></i><b>2.1.3</b> Readings &amp; Resources</a></li>
<li class="chapter" data-level="2.1.4" data-path="oneway.html"><a href="oneway.html#packages"><i class="fa fa-check"></i><b>2.1.4</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="oneway.html"><a href="oneway.html#workflow-for-one-way-anova"><i class="fa fa-check"></i><b>2.2</b> Workflow for One-Way ANOVA</a></li>
<li class="chapter" data-level="2.3" data-path="oneway.html"><a href="oneway.html#research-vignette"><i class="fa fa-check"></i><b>2.3</b> Research Vignette</a><ul>
<li class="chapter" data-level="2.3.1" data-path="oneway.html"><a href="oneway.html#data-simulation"><i class="fa fa-check"></i><b>2.3.1</b> Data Simulation</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="oneway.html"><a href="oneway.html#working-the-problem"><i class="fa fa-check"></i><b>2.4</b> Working the Problem</a><ul>
<li class="chapter" data-level="2.4.1" data-path="oneway.html"><a href="oneway.html#preparing-and-uploading-data"><i class="fa fa-check"></i><b>2.4.1</b> Preparing and Uploading Data</a></li>
<li class="chapter" data-level="2.4.2" data-path="oneway.html"><a href="oneway.html#exploring-the-distributional-characteristics-numerically"><i class="fa fa-check"></i><b>2.4.2</b> Exploring the Distributional Characteristics Numerically</a></li>
<li class="chapter" data-level="2.4.3" data-path="oneway.html"><a href="oneway.html#exploring-the-distributional-characteristics-graphically"><i class="fa fa-check"></i><b>2.4.3</b> Exploring the Distributional Characteristics Graphically</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="oneway.html"><a href="oneway.html#understanding-anova-with-hand-calculations"><i class="fa fa-check"></i><b>2.5</b> Understanding ANOVA with <em>Hand Calculations</em></a><ul>
<li class="chapter" data-level="2.5.1" data-path="oneway.html"><a href="oneway.html#sums-of-squares-total"><i class="fa fa-check"></i><b>2.5.1</b> Sums of Squares Total</a></li>
<li class="chapter" data-level="2.5.2" data-path="oneway.html"><a href="oneway.html#sums-of-squares-for-the-model-or-between"><i class="fa fa-check"></i><b>2.5.2</b> Sums of Squares for the Model (or Between)</a></li>
<li class="chapter" data-level="2.5.3" data-path="oneway.html"><a href="oneway.html#sums-of-squares-residual-or-within"><i class="fa fa-check"></i><b>2.5.3</b> Sums of Squares Residual (or within)</a></li>
<li class="chapter" data-level="2.5.4" data-path="oneway.html"><a href="oneway.html#relationship-between-ss_t-ss_m-and-ss_r."><i class="fa fa-check"></i><b>2.5.4</b> Relationship between <span class="math inline">\(SS_T\)</span>, <span class="math inline">\(SS_M\)</span>, and <span class="math inline">\(SS_R\)</span>.</a></li>
<li class="chapter" data-level="2.5.5" data-path="oneway.html"><a href="oneway.html#mean-squares-model-residual"><i class="fa fa-check"></i><b>2.5.5</b> Mean Squares Model &amp; Residual</a></li>
<li class="chapter" data-level="2.5.6" data-path="oneway.html"><a href="oneway.html#calculating-the-f-statistic"><i class="fa fa-check"></i><b>2.5.6</b> Calculating the <em>F</em>-Statistic</a></li>
<li class="chapter" data-level="2.5.7" data-path="oneway.html"><a href="oneway.html#source-table-games"><i class="fa fa-check"></i><b>2.5.7</b> Source Table Games</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="working-the-one-way-anova-in-r.html"><a href="working-the-one-way-anova-in-r.html"><i class="fa fa-check"></i>Working the One-Way ANOVA in R</a><ul>
<li class="chapter" data-level="2.5.8" data-path="working-the-one-way-anova-in-r.html"><a href="working-the-one-way-anova-in-r.html#evaluating-the-statistical-assumptions"><i class="fa fa-check"></i><b>2.5.8</b> Evaluating the statistical assumptions</a></li>
<li class="chapter" data-level="2.5.9" data-path="working-the-one-way-anova-in-r.html"><a href="working-the-one-way-anova-in-r.html#is-it-normally-distributed"><i class="fa fa-check"></i><b>2.5.9</b> Is it normally distributed?</a></li>
<li class="chapter" data-level="2.5.10" data-path="working-the-one-way-anova-in-r.html"><a href="working-the-one-way-anova-in-r.html#evaluating-the-homogeneity-of-variance-assumption-with-levenes-test"><i class="fa fa-check"></i><b>2.5.10</b> Evaluating the Homogeneity of Variance Assumption with Levene’s Test</a></li>
<li class="chapter" data-level="2.6" data-path="working-the-one-way-anova-in-r.html"><a href="working-the-one-way-anova-in-r.html#compute-the-omnibus-anova"><i class="fa fa-check"></i><b>2.6</b> Compute the omnibus ANOVA</a><ul>
<li class="chapter" data-level="2.6.1" data-path="working-the-one-way-anova-in-r.html"><a href="working-the-one-way-anova-in-r.html#effect-size-for-the-one-way-anova"><i class="fa fa-check"></i><b>2.6.1</b> Effect size for the one-way ANOVA</a></li>
<li class="chapter" data-level="2.6.2" data-path="working-the-one-way-anova-in-r.html"><a href="working-the-one-way-anova-in-r.html#follow-up-to-the-omnibus"><i class="fa fa-check"></i><b>2.6.2</b> Follow-up to the omnibus</a></li>
<li class="chapter" data-level="2.6.3" data-path="working-the-one-way-anova-in-r.html"><a href="working-the-one-way-anova-in-r.html#which-set-of-follow-up-tests-do-we-use"><i class="fa fa-check"></i><b>2.6.3</b> Which set of follow-up tests do we use?</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="working-the-one-way-anova-in-r.html"><a href="working-the-one-way-anova-in-r.html#but-what-if-we-violated-the-homogeneity-of-variance-test"><i class="fa fa-check"></i><b>2.7</b> But what if we violated the Homogeneity of Variance test?</a></li>
<li class="chapter" data-level="2.8" data-path="working-the-one-way-anova-in-r.html"><a href="working-the-one-way-anova-in-r.html#power-analysis"><i class="fa fa-check"></i><b>2.8</b> Power Analysis</a></li>
<li class="chapter" data-level="2.9" data-path="working-the-one-way-anova-in-r.html"><a href="working-the-one-way-anova-in-r.html#apa-style-results"><i class="fa fa-check"></i><b>2.9</b> APA Style Results</a></li>
<li class="chapter" data-level="2.10" data-path="working-the-one-way-anova-in-r.html"><a href="working-the-one-way-anova-in-r.html#bonus-reel"><i class="fa fa-check"></i><b>2.10</b> Bonus Reel:</a></li>
<li class="chapter" data-level="2.11" data-path="working-the-one-way-anova-in-r.html"><a href="working-the-one-way-anova-in-r.html#references"><i class="fa fa-check"></i><b>2.11</b> References</a></li>
</ul></li>
<li class="divider"></li>
#<li><a href="https:link" target="_blank">Open access book-in-progress</br>
<li><a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a></li>
  <li><a href="https://bookdown.org" target="_blank">Built with Bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">DRAFT: ReCentering Psych Stats</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="working-the-one-way-anova-in-r" class="section level1 unnumbered">
<h1>Working the One-Way ANOVA in R</h1>
<p>Let’s rework the problem in R.</p>
<div id="evaluating-the-statistical-assumptions" class="section level3">
<h3><span class="header-section-number">2.5.8</span> Evaluating the statistical assumptions</h3>
<p>All statistical tests have some assumptions about the data. The one-way ANOVA has four assumptions:</p>
<ul>
<li>The dependent variable is normally distributed for each of the pouplations as defined by the different levels of the factor. We will examine this by
<ul>
<li>evaluating skew and kurtosis</li>
<li>visually inspecting the distribution</li>
<li>conduct a Shapiro Wilks test</li>
<li>examine a QQ plot</li>
</ul></li>
<li>The variances of the dependent variable are the same for all populations. This is often termed the <em>homogeneity of variance</em> assumption. We will examine this with
<ul>
<li>Levene’s Test</li>
</ul></li>
<li>The cases represent <em>random</em> samples from the populations and scores on the test variable are independent of each other. That is, comparing related cases (e.g., parent/child, manager/employee, time1/time2) must be completed by another statistic such as repeated measures ANOVA or dyadic data analysis.
<ul>
<li><em>Independence</em> in observations is a research design issue. ANOVA not robust to violating this assumption. When observations are correlated/dependent there is a dramatic increase in Type I error.</li>
</ul></li>
<li>The dependent variable is measured on an interval scale.
<ul>
<li>This is also a research design issue. If the dependent variable is categorical, another statistic (such as logistic regression) should be chosen.</li>
</ul></li>
</ul>
</div>
<div id="is-it-normally-distributed" class="section level3">
<h3><span class="header-section-number">2.5.9</span> Is it normally distributed?</h3>
<p>From the <em>psych</em> package, the <em>describe()</em> function can be used to provide descriptives of continuous (interval, ratio) variables. In this simple example, we can specify the specific continuous, DV.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="working-the-one-way-anova-in-r.html#cb56-1"></a><span class="kw">library</span>(psych)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;psych&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:ggplot2&#39;:
## 
##     %+%, alpha</code></pre>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="working-the-one-way-anova-in-r.html#cb59-1"></a><span class="kw">describe</span>(accSIM30<span class="op">$</span>Accurate)</span></code></pre></div>
<pre><code>##    vars  n mean   sd median trimmed  mad  min max range  skew kurtosis   se
## X1    1 90  1.8 0.66    1.8    1.83 0.56 0.15   3  2.85 -0.33    -0.07 0.07</code></pre>
<p>If we want descriptives for each level of the grouping variable (factor), we can use the <em>describeBy()</em> function of the <em>psych</em> package. The order of entry within the script is the DV followed by the grouping variable (IV).</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="working-the-one-way-anova-in-r.html#cb61-1"></a>des.mat &lt;-<span class="st"> </span><span class="kw">describeBy</span> (Accurate <span class="op">~</span><span class="st"> </span>COND, <span class="dt">mat=</span><span class="ot">TRUE</span>, <span class="dt">digits=</span><span class="dv">3</span>, <span class="dt">data=</span>accSIM30) <span class="co">#unnecessary to create an object, but an object allows you to do cool stuff, like write it to a .csv file</span></span>
<span id="cb61-2"><a href="working-the-one-way-anova-in-r.html#cb61-2"></a></span>
<span id="cb61-3"><a href="working-the-one-way-anova-in-r.html#cb61-3"></a><span class="co">#describeBy(accSIM30$Accurate, accSIM30$COND, mat=TRUE)</span></span>
<span id="cb61-4"><a href="working-the-one-way-anova-in-r.html#cb61-4"></a></span>
<span id="cb61-5"><a href="working-the-one-way-anova-in-r.html#cb61-5"></a>des.mat <span class="co">#let&#39;s you see the matrix object</span></span></code></pre></div>
<pre><code>##     item  group1 vars  n  mean    sd median trimmed   mad   min   max range
## X11    1 Control    1 30 1.877 0.479  1.811   1.872 0.460 0.854 2.721 1.867
## X12    2     Low    1 30 2.047 0.573  2.049   2.053 0.534 0.922 3.000 2.078
## X13    3    High    1 30 1.474 0.765  1.498   1.469 0.646 0.153 2.935 2.782
##       skew kurtosis    se
## X11  0.134   -0.756 0.087
## X12  0.017   -0.872 0.105
## X13 -0.034   -0.789 0.140</code></pre>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="working-the-one-way-anova-in-r.html#cb63-1"></a><span class="kw">write.csv</span> (des.mat, <span class="dt">file=</span><span class="st">&quot;Table1.csv&quot;</span>) <span class="co">#optional to write it to a .csv file</span></span></code></pre></div>
<p>Skew and kurtosis speaks to normal distributions. As we described before, the skew and kurtosis indices in the psych package are reported as <em>z</em> scores. Regarding skew, values &gt; 3.0 are generally considered “severely skewed.” Regarding kurtosis, “severely kurtotic” is argued anywhere &gt; 8 to 20 <span class="citation">(Kline, <a href="#ref-kline_principles_2016" role="doc-biblioref">2016</a>)</span>.</p>
<p>The <strong>Shapiro-Wilk</strong> test is a statistical test of the hypothesis that the distribution of the data as a whole deviates from a comparable normal distribution. If the test is non-significant (<em>p</em> &gt;.05) it tells us that the distribution of the sample is not significantly different from a normal distribution. If, however, the test is significant (<em>p</em> &lt; .05) then the distribution in question is significantly different from a normal distribution.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="working-the-one-way-anova-in-r.html#cb64-1"></a><span class="kw">shapiro.test</span>(accSIM30<span class="op">$</span>Accurate)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  accSIM30$Accurate
## W = 0.97413, p-value = 0.06931</code></pre>
<p>The <span class="math inline">\(p\)</span> value (<span class="math inline">\(p\)</span> = 0.069) is just barely above .05 tells us that the accuracy data does not deviate from a statistically significant distribution.</p>
<p>There are limitations to the Shapiro-Wilk test. As the dataset being evaluated gets larger, the Shapiro-Wilk test becomes more sensitive to small deviations which leads to a greater probability of rejecting the null hypothesis (null hypothesis being the values come from a normal distribution). Green and Salkind <span class="citation">(<a href="#ref-green_using_2014" role="doc-biblioref">2014</a>)</span> advise that ANOVA is relatively robust to violations of normality if there are at least 15 cases per cell and the design is reasonably balanced (i.e., equal cell sizes).</p>
<p>So far, so good for being reasonably normally distributed.</p>
</div>
<div id="evaluating-the-homogeneity-of-variance-assumption-with-levenes-test" class="section level3">
<h3><span class="header-section-number">2.5.10</span> Evaluating the Homogeneity of Variance Assumption with Levene’s Test</h3>
<p>An ANOVA assumption is that variances of the dependent variable for each level of the independent variable be similarly distributed. We can test this with Levene’s test. We want this to be non-significant (<span class="math inline">\(p\)</span> &gt; .05). If violated, we need to use an ANOVA test that is "robust to the violation of the homogeneity of variance (e.g., Welch’s oneway).</p>
<p>In R, Levene’s test is found in the <em>car</em> package.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="working-the-one-way-anova-in-r.html#cb66-1"></a><span class="kw">library</span>(car)</span></code></pre></div>
<pre><code>## Loading required package: carData</code></pre>
<pre><code>## 
## Attaching package: &#39;car&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:psych&#39;:
## 
##     logit</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     recode</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     some</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="working-the-one-way-anova-in-r.html#cb72-1"></a><span class="kw">leveneTest</span> (Accurate <span class="op">~</span><span class="st"> </span>COND, accSIM30, <span class="dt">center=</span>mean)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = mean)
##       Df F value Pr(&gt;F)
## group  2   2.274  0.109
##       87</code></pre>
<p>We write the result of the Levene’s as <span class="math inline">\(F\)</span>(2,87) = 2.274, <span class="math inline">\(p\)</span> = 0.109 Because <span class="math inline">\(p\)</span> &gt; .05, we know that the result is nonsignficant – that the variances of the three groups are not statistically significantly different than each other.</p>
<p>IF the results had been statistically significantly different, we would have needed to use a Welch’s <span class="math inline">\(F\)</span> or robust version of ANOVA.</p>
</div>
<div id="compute-the-omnibus-anova" class="section level2">
<h2><span class="header-section-number">2.6</span> Compute the omnibus ANOVA</h2>
<p>ANOVA is a special case of the general linear model (regression is a “not so special case” of the general linear model).</p>
<p>We use the linear model function, <em>aov()</em> to run the analysis.</p>
<p>In the code below, we predict Accuracy from COND (3 levels: control, low, high).</p>
<p>By assigning the results of the <em>aov()</em> function to an object (accBYcond) we can then use that object (or model) in other functions to get details of our analysis.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="working-the-one-way-anova-in-r.html#cb74-1"></a>accBYcond &lt;-<span class="st"> </span><span class="kw">aov</span>(Accurate <span class="op">~</span><span class="st"> </span>COND, <span class="dt">data =</span> accSIM30) <span class="co">#DV ~ IV  I say, &quot;DV by IV&quot;</span></span>
<span id="cb74-2"><a href="working-the-one-way-anova-in-r.html#cb74-2"></a><span class="kw">summary</span> (accBYcond) <span class="co">#ANOVA output</span></span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value  Pr(&gt;F)   
## COND         2   5.20   2.598   6.817 0.00178 **
## Residuals   87  33.15   0.381                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Inserting our <em>aov()</em> object into the summary command gets us the data in ANOVA Source Table that we manually created above.</p>
<p>The values we see map onto those we calculated by hand. Our Sums of Squares for the Model (5.20) plus Sums of Squares for the Residual (33.15) add to the Sums of Squares Total (38.35) we calculated by hand.</p>
<p>Dividing the two Sums of Squares by their respective DF results in the Mean Squared.</p>
<p>Dividing Mean Squared for the Model (COND) by Mean Squared for the Residual (2.598/-.381) provides the <em>F</em> value. By using a table of <em>F</em> critical values, we already knew that our <em>F</em> value exceeded the value in the table of critical values. Here we see that <em>p</em> = 0.00178.</p>
<p>The “<em>F</em> string” for your results section should be written like this: <em>F</em> (2, 87) = 6.817, <em>p</em> = 0.002.</p>
<p>The <em>aov()</em> object holds all sorts of values.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="working-the-one-way-anova-in-r.html#cb76-1"></a><span class="kw">names</span>(accBYcond)</span></code></pre></div>
<pre><code>##  [1] &quot;coefficients&quot;  &quot;residuals&quot;     &quot;effects&quot;       &quot;rank&quot;         
##  [5] &quot;fitted.values&quot; &quot;assign&quot;        &quot;qr&quot;            &quot;df.residual&quot;  
##  [9] &quot;contrasts&quot;     &quot;xlevels&quot;       &quot;call&quot;          &quot;terms&quot;        
## [13] &quot;model&quot;</code></pre>
<p>If we know the functions to apply to it, we can retrieve them; <em>summary()</em> is one of the most common used with ANOVA, but it’s not the only one.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="working-the-one-way-anova-in-r.html#cb78-1"></a><span class="kw">model.tables</span> (accBYcond, <span class="st">&quot;means&quot;</span>)</span></code></pre></div>
<pre><code>## Tables of means
## Grand mean
##          
## 1.799009 
## 
##  COND 
## COND
## Control     Low    High 
##  1.8769  2.0465  1.4736</code></pre>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="working-the-one-way-anova-in-r.html#cb80-1"></a><span class="kw">plot</span>(accBYcond) </span></code></pre></div>
<p><img src="ReCenterPsychStats_files/figure-html/plot%20function-1.svg" width="672" /><img src="ReCenterPsychStats_files/figure-html/plot%20function-2.svg" width="672" /><img src="ReCenterPsychStats_files/figure-html/plot%20function-3.svg" width="672" /><img src="ReCenterPsychStats_files/figure-html/plot%20function-4.svg" width="672" /></p>
<p>The <em>aov()</em> command has a quickplot feature. The first of the four plots fits the residuals. We already know from Levene’s that we did not violate the homogeneity of variance test. With its straight line, this plot shows an equal spread across the three groups.</p>
<p>When the dots of the Q-Q plot map onto the diagonal, we have some indication of normality of the residuals (we want residuals to be normally distributed).</p>
<div id="effect-size-for-the-one-way-anova" class="section level3">
<h3><span class="header-section-number">2.6.1</span> Effect size for the one-way ANOVA</h3>
<p><strong>Eta squared</strong> is one of the most commonly used measures of effect. It refers to the proportion of variability in the DV/outcome variable that can be explained in terms of the IV/predictor. Traditional interpretive values are similar to the Pearson’s <em>r</em>:</p>
<p>0 = no relationship
.02 = small
.13 = medium
.26 = large
1 = a perfect (one-to-one) correspondence</p>
<p>More interpretive info can be found here: <a href="https://imaging.mrc-cbu.cam.ac.uk/statswiki/FAQ/effectSize" class="uri">https://imaging.mrc-cbu.cam.ac.uk/statswiki/FAQ/effectSize</a></p>
<p>The formula is straightforward:</p>
<p><span class="math display">\[\eta ^{2}=\frac{SS_{M}}{SS_{T}}\]</span>
For us:</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="working-the-one-way-anova-in-r.html#cb81-1"></a><span class="fl">5.20</span> <span class="op">/</span><span class="st"> </span>(<span class="fl">5.20</span> <span class="op">+</span><span class="st"> </span><span class="fl">33.15</span>)</span></code></pre></div>
<pre><code>## [1] 0.1355932</code></pre>
<p>The <em>lsr</em> package includes an eta-squared calculator:</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="working-the-one-way-anova-in-r.html#cb83-1"></a><span class="kw">library</span>(lsr)</span>
<span id="cb83-2"><a href="working-the-one-way-anova-in-r.html#cb83-2"></a><span class="kw">etaSquared</span>(accBYcond)</span></code></pre></div>
<pre><code>##         eta.sq eta.sq.part
## COND 0.1354894   0.1354894</code></pre>
<p>Notice that there are two effect sizes. We described eta-squared. Partial eta-squared is the effect size reported in SPSS. There’s a long history of debate about which to use. In certain circumstances (especially in more complicated analyses), partial-eta squared can be a bit more generous and many prefer the reporting of eta squared.</p>
<p><strong>To recap so far</strong>: We have rejected the <span class="math inline">\(H_O\)</span>. That is, our omnibus ANOVA shows that there is a statistically significant difference somewhere in our model with a medium effect size, $ F(2, 87) = 6.817, p = 0.002, ^2 = .14$</p>
</div>
<div id="follow-up-to-the-omnibus" class="section level3">
<h3><span class="header-section-number">2.6.2</span> Follow-up to the omnibus</h3>
<p>The <em>F</em>-test associated with the one-way ANOVA is the <em>omnibus</em> – giving the result for the overall test. If it is significant, we know that there is at least one pair of cells where there is a statistically significant difference. We have several ways (each with its own strengths/limitations) to figure out where these differences lie.</p>
<div id="option-1-post-hoc-pairwise-comparisons" class="section level4">
<h4><span class="header-section-number">2.6.2.1</span> OPTION 1: Post hoc, pairwise, comparisons</h4>
<ul>
<li>for exploratory work when no firm hypotheses were articulated a priori</li>
<li>comparing the mean of all combinations of pairs of experimental conditions</li>
<li>less powerful than planned comparisons b/c strict criterion for significance must be used</li>
</ul>
<p><a href="https://stats.idre.ucla.edu/r/faq/how-can-i-do-post-hoc-pairwise-comparisons-in-r/" class="uri">https://stats.idre.ucla.edu/r/faq/how-can-i-do-post-hoc-pairwise-comparisons-in-r/</a></p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="working-the-one-way-anova-in-r.html#cb85-1"></a><span class="kw">pairwise.t.test</span>(accSIM30<span class="op">$</span>Accurate, accSIM30<span class="op">$</span>COND, <span class="dt">p.adj =</span> <span class="st">&quot;none&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  accSIM30$Accurate and accSIM30$COND 
## 
##      Control Low    
## Low  0.29016 -      
## High 0.01321 0.00054
## 
## P value adjustment method: none</code></pre>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="working-the-one-way-anova-in-r.html#cb87-1"></a><span class="co">#can swap &quot;bonf&quot; or &quot;holm&quot; for p.adj</span></span></code></pre></div>
<p>It’s annoying that the <em>pairwise.t.test()</em> requires re-specification of the DV by IV. Navarro’s <span class="citation">(<a href="#ref-navarro_book_2020" role="doc-biblioref">2020</a><a href="#ref-navarro_book_2020" role="doc-biblioref">a</a>)</span> <em>lsr</em> package, we can simply use the <em>aov()</em> object we created (but since she may revise it, I’ve left pairwise.t.test).</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="working-the-one-way-anova-in-r.html#cb88-1"></a><span class="kw">posthocPairwiseT</span>(accBYcond, <span class="dt">p.adjust.method =</span> <span class="st">&quot;none&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  Accurate and COND 
## 
##      Control Low    
## Low  0.29016 -      
## High 0.01321 0.00054
## 
## P value adjustment method: none</code></pre>
<p>Reporting results of these typically involves mean differences and <em>p</em> values; this output provides only p values (we can calculate mean differeces, by hand).</p>
<p><strong>Should we be concerned about Type I error?"</strong></p>
<p>Recall that <em>Type I error</em> is the the concern about false positive – that we would incorrectly reject a true null hypothesis (that we would say that there is a statistically significant difference when there is not one). This concern increases when we have a large number of pairwise comparisons.</p>
<p>Green and Salkind <span class="citation">(<a href="#ref-green_using_2014" role="doc-biblioref">2014</a>)</span> review three options for managing Type I error.</p>
<ul>
<li>Traditional Bonferroni:
<ul>
<li>adjusts the <em>p</em> value upward by multiplying it (the raw <em>p</em> values) by the number of comparisons being completed. This holds the <em>total</em> Type I error rate across these tests to <span class="math inline">\(\alpha\)</span> (usually .05). The traditional Bonerroni is simple, and therefore attractive, but when <em>p</em> values hover around .05, it can be too restrictive.</li>
</ul></li>
<li>Holms sequential Bonferonni:</li>
<li>We’ll describe this in more detail later, but it essentially allows us to rank order the comparisons by their <em>p</em> value (smallest to largest). We determine the significance of each <em>p</em> value <em>sequentially.</em> It’s pretty slick.</li>
<li>LSD method:</li>
<li>Allowed only when there are only 3 pairwise comparisons among 3 groups. Since this is one of those circumstances, I would not use the Bonferroni or Holm’s sequential Bonferroni. Rather, if I wanted to report all three comparisons, I would not adjust the <em>p</em> values and claim the LSD (citing Green &amp; Salkind, 2014).</li>
</ul>
<p>There is, though, an even more powerful approach…</p>
</div>
<div id="option-2-planned-contrasts." class="section level4">
<h4><span class="header-section-number">2.6.2.2</span> OPTION 2: Planned contrasts.</h4>
<ul>
<li>theory-driven comparisons constructed prior to data collection</li>
<li>based on the idea of partitioning the variance created by the overall effect of group differences into gradually smaller portions of variance</li>
<li>more powerful than post hoc tests</li>
</ul>
<p>Planned contrasts involve further considerations regarding the <em>partitioning of variance.</em></p>
<ul>
<li>There will always be <em>k</em>-1 contrasts.</li>
<li>Each contrast must involve ONLY TWO chunks of variance.</li>
</ul>
<p><em>Orthogonal</em> contrasts are even more sophisticated. The bottom line: if a group is singled out in one comparison it should be excluded from subsequent contrasts.</p>
<p>The typical, orthogonal scenario with three groups is, only two contrasts:</p>
<p>Control versus Low and High (because control was excluded, it should not reappear)
Low versus High</p>
<p>Underlying the <em>aov()</em> program is the linear model. We could have used it for the omnibus ANOVA, but it has clunky output.</p>
<p>We use it now to retrieve some contrast information. The code below is a planned comparison that uses the coding in the datase to compare the lowest coded group (placebo was 1, low was 2, high was 3) to the other two groups.</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="working-the-one-way-anova-in-r.html#cb90-1"></a><span class="kw">summary.lm</span>(accBYcond)</span></code></pre></div>
<pre><code>## 
## Call:
## aov(formula = Accurate ~ COND, data = accSIM30)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.32063 -0.36424 -0.01944  0.33736  1.46146 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   1.8769     0.1127  16.654   &lt;2e-16 ***
## CONDLow       0.1696     0.1594   1.064   0.2902    
## CONDHigh     -0.4032     0.1594  -2.530   0.0132 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.6173 on 87 degrees of freedom
## Multiple R-squared:  0.1355, Adjusted R-squared:  0.1156 
## F-statistic: 6.817 on 2 and 87 DF,  p-value: 0.001776</code></pre>
<p>In our results we see that there was not a statistically significant difference between COND_Control COND_Low (<em>p</em> = 0.2902). There were</p>
<p>Note that these tests are conducted as <em>t</em> tests. Why? We are comparing only two groups and can use the <em>t</em>. distribution.</p>
<p>It’s quite possible we want something different.</p>
<p><strong>Step 1: </strong> Specify our contrasts</p>
<ul>
<li>Specifying the contrasts means you know their order</li>
<li>We created an ordered factor with Control, Low, High as the order.</li>
</ul>
<p><strong>Step 2:</strong> Bind them together</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="working-the-one-way-anova-in-r.html#cb92-1"></a><span class="co">#Contrast1  compares Control against the combined effects of Low and High.</span></span>
<span id="cb92-2"><a href="working-the-one-way-anova-in-r.html#cb92-2"></a>contrast1 &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="op">-</span><span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">1</span>)</span>
<span id="cb92-3"><a href="working-the-one-way-anova-in-r.html#cb92-3"></a></span>
<span id="cb92-4"><a href="working-the-one-way-anova-in-r.html#cb92-4"></a><span class="co">#Contrast2 excludes Control; compares Low to High.</span></span>
<span id="cb92-5"><a href="working-the-one-way-anova-in-r.html#cb92-5"></a>contrast2 &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>,<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>)</span>
<span id="cb92-6"><a href="working-the-one-way-anova-in-r.html#cb92-6"></a><span class="kw">contrasts</span>(accSIM30<span class="op">$</span>COND)&lt;-<span class="kw">cbind</span>(contrast1, contrast2)</span>
<span id="cb92-7"><a href="working-the-one-way-anova-in-r.html#cb92-7"></a>accSIM30<span class="op">$</span>COND</span></code></pre></div>
<pre><code>##  [1] High    High    High    High    High    High    High    High    High   
## [10] High    High    High    High    High    High    High    High    High   
## [19] High    High    High    High    High    High    High    High    High   
## [28] High    High    High    Low     Low     Low     Low     Low     Low    
## [37] Low     Low     Low     Low     Low     Low     Low     Low     Low    
## [46] Low     Low     Low     Low     Low     Low     Low     Low     Low    
## [55] Low     Low     Low     Low     Low     Low     Control Control Control
## [64] Control Control Control Control Control Control Control Control Control
## [73] Control Control Control Control Control Control Control Control Control
## [82] Control Control Control Control Control Control Control Control Control
## attr(,&quot;contrasts&quot;)
##         contrast1 contrast2
## Control        -2         0
## Low             1        -1
## High            1         1
## Levels: Control Low High</code></pre>
<p>Thinking back to the hand-calculations and contrast mapping, the table of weights that R just produced confirms that C
* Contrast 1 compares the placebo group against the two experimental groups.<br />
* Contrast 2 compares the low dose group to the high dose group.</p>
<p><strong>Step 3:</strong> Create a new <em>aov()</em> model</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="working-the-one-way-anova-in-r.html#cb94-1"></a>accPlanned &lt;-<span class="st"> </span><span class="kw">aov</span>(Accurate <span class="op">~</span><span class="st"> </span>COND, <span class="dt">data =</span> accSIM30)</span>
<span id="cb94-2"><a href="working-the-one-way-anova-in-r.html#cb94-2"></a><span class="kw">summary.lm</span>(accPlanned)</span></code></pre></div>
<pre><code>## 
## Call:
## aov(formula = Accurate ~ COND, data = accSIM30)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.32063 -0.36424 -0.01944  0.33736  1.46146 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    1.79901    0.06507  27.648  &lt; 2e-16 ***
## CONDcontrast1 -0.03894    0.04601  -0.846 0.399727    
## CONDcontrast2 -0.28643    0.07969  -3.594 0.000539 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.6173 on 87 degrees of freedom
## Multiple R-squared:  0.1355, Adjusted R-squared:  0.1156 
## F-statistic: 6.817 on 2 and 87 DF,  p-value: 0.001776</code></pre>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="working-the-one-way-anova-in-r.html#cb96-1"></a><span class="kw">contrasts</span>(accSIM30<span class="op">$</span>COND)&lt;-<span class="kw">cbind</span>(<span class="kw">c</span>(<span class="op">-</span><span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">1</span>), <span class="kw">c</span>(<span class="dv">0</span>,<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>))</span></code></pre></div>
<p>These planned contrasts show that when the control condition is compared to the combined low and high racial loading conditions, there is not a statistically significant difference, <em>t</em>(87) = -0.846, <em>p</em> = 0.400. However, when the low and high racial loading conditions are compared, there is a statistically significant difference, <em>t</em>(87) = -3.594, <em>p</em> = 0.001.</p>
</div>
<div id="what-about-trend-polynomial-analysis-as-an-effect" class="section level4">
<h4><span class="header-section-number">2.6.2.3</span> What about trend (polynomial) analysis (as an effect)?</h4>
<p>Polynomial contrasts let us see if there is a linear (or curvilinear) pattern to the data. To detect a trend, the data must be coded in an ascending order…and it needs to be a sensible comparison. In the viagra data, it is.</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="working-the-one-way-anova-in-r.html#cb97-1"></a><span class="kw">contrasts</span>(accSIM30<span class="op">$</span>COND)&lt;-<span class="kw">contr.poly</span>(<span class="dv">3</span>)</span>
<span id="cb97-2"><a href="working-the-one-way-anova-in-r.html#cb97-2"></a>accTrend&lt;-<span class="kw">aov</span>(Accurate <span class="op">~</span><span class="st"> </span>COND, <span class="dt">data =</span> accSIM30)</span>
<span id="cb97-3"><a href="working-the-one-way-anova-in-r.html#cb97-3"></a><span class="kw">summary.lm</span>(accTrend)</span></code></pre></div>
<pre><code>## 
## Call:
## aov(formula = Accurate ~ COND, data = accSIM30)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.32063 -0.36424 -0.01944  0.33736  1.46146 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.79901    0.06507   27.65  &lt; 2e-16 ***
## COND.L      -0.28514    0.11270   -2.53  0.01321 *  
## COND.Q      -0.30312    0.11270   -2.69  0.00857 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.6173 on 87 degrees of freedom
## Multiple R-squared:  0.1355, Adjusted R-squared:  0.1156 
## F-statistic: 6.817 on 2 and 87 DF,  p-value: 0.001776</code></pre>
</div>
</div>
<div id="which-set-of-follow-up-tests-do-we-use" class="section level3">
<h3><span class="header-section-number">2.6.3</span> Which set of follow-up tests do we use?</h3>
<p>It depends! What best tells your story?</p>
<ul>
<li>If the post-hoc comparisons are robustly statistically significant (and controlling Type I error is not going to change that signifcance), I think this provides good information – I would report those.</li>
<li>If <em>p</em> values are hovering around 0.05, an orthogonal contrast will offer more power because
<ul>
<li>a <em>k</em> - 1 comparison will be more powerful</li>
<li>a priori theory is compelling</li>
</ul></li>
<li>The polynomial can be a nice addition if there is a linear or quadratic relationship that is sensible or interesting.</li>
</ul>
<p>Although I would report EITHER the post-hoc or planned contrasts, I will sometimes add a polynomial if it adds to the story.</p>
</div>
</div>
<div id="but-what-if-we-violated-the-homogeneity-of-variance-test" class="section level2">
<h2><span class="header-section-number">2.7</span> But what if we violated the Homogeneity of Variance test?</h2>
<p>Built into <em>R</em> is the <em>oneway.test</em> that returns Welch’s <em>F</em> which is robust to violation of the homogeneity of variance assumption.</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="working-the-one-way-anova-in-r.html#cb99-1"></a><span class="kw">oneway.test</span> (Accurate <span class="op">~</span><span class="st"> </span>COND, <span class="dt">data =</span> accSIM30)</span></code></pre></div>
<pre><code>## 
##  One-way analysis of means (not assuming equal variances)
## 
## data:  Accurate and COND
## F = 5.3691, num df = 2.00, denom df = 56.22, p-value = 0.007346</code></pre>
<p>Note that the denominator <em>df</em> is now 56.22 (not 87) and <em>p</em> value is bigger (it was .00178). The Welch’s <em>F</em> is more “conservative,” to avoid making a Type I error. While it doesn’t matter in this case, if it were a study where the <em>p</em> value was closer to .05, it could make a difference. These are some of the tradeoffs made in order to “trust” the results.</p>
</div>
<div id="power-analysis" class="section level2">
<h2><span class="header-section-number">2.8</span> Power Analysis</h2>
<p><a href="https://www.statmethods.net/stats/power.html" class="uri">https://www.statmethods.net/stats/power.html</a></p>
<p>Power analysis allows us to determine the sample size required to detect an effect of a given size with a given degree of confidence. In reverse, it allows us to determine the probability of detecting an effect of a given size with a given level of confidence. If the probability is unacceptably low, we may want to revise or stop.</p>
<p>There are four interrelating elements of power:</p>
<ol style="list-style-type: decimal">
<li>Sample size, <em>N</em></li>
<li>Effect size
<ul>
<li>For one-way ANOVAs, Cohen suggests that f values of 0.1, 0.25, and 0.4 represent small, medium, and large effect sizes, respectively.</li>
</ul></li>
<li>Significance level = P(Type I error)
<ul>
<li>the probability of finding an effect that is not there</li>
</ul></li>
<li>power = 1 - P(Type II error)</li>
</ol>
<ul>
<li>the probability of finding an effect that is there</li>
</ul>
<p>If we have any three of these values, we can calculate the fourth.</p>
<p>In Champely’s <em>pwr</em> package, we can conduct a power analysis for a variety of designs, including a balanced (i.e., equal/roughly equal cell sizes).</p>
<p>The pwr.anova.test has four parmeters:</p>
<p>k = # groups
n = sample size
sig.level = p value that you will use
power = .80 is the standard value</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="working-the-one-way-anova-in-r.html#cb101-1"></a><span class="kw">library</span>(pwr)</span>
<span id="cb101-2"><a href="working-the-one-way-anova-in-r.html#cb101-2"></a></span>
<span id="cb101-3"><a href="working-the-one-way-anova-in-r.html#cb101-3"></a><span class="kw">pwr.anova.test</span> (<span class="dt">k =</span> <span class="dv">3</span>, <span class="dt">f =</span> <span class="fl">.25</span>, <span class="dt">sig.level =</span> <span class="fl">.05</span>, <span class="dt">power =</span> <span class="fl">.80</span>)</span></code></pre></div>
<pre><code>## 
##      Balanced one-way analysis of variance power calculation 
## 
##               k = 3
##               n = 52.3966
##               f = 0.25
##       sig.level = 0.05
##           power = 0.8
## 
## NOTE: n is number in each group</code></pre>
<p>This result suggested that we would need 52 people per group.</p>
<p>Our effect size was an <span class="math inline">\(\eta^2 = .13\)</span>. Using an effect size converter, we can learn that it is an <em>f</em> of .386. We could actually reanalyze to see how many fewer people we needed.</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="working-the-one-way-anova-in-r.html#cb103-1"></a><span class="kw">pwr.anova.test</span> (<span class="dt">k =</span> <span class="dv">3</span>, <span class="dt">f =</span> <span class="fl">.386</span>, <span class="dt">sig.level =</span> <span class="fl">.05</span>, <span class="dt">power =</span> <span class="fl">.80</span>)</span></code></pre></div>
<pre><code>## 
##      Balanced one-way analysis of variance power calculation 
## 
##               k = 3
##               n = 22.58384
##               f = 0.386
##       sig.level = 0.05
##           power = 0.8
## 
## NOTE: n is number in each group</code></pre>
<p>This is a little funny – that was actually our sample size, but I increased it because our simulated data did not have statistically significant results.</p>
</div>
<div id="apa-style-results" class="section level2">
<h2><span class="header-section-number">2.9</span> APA Style Results</h2>
<p>A one-way analysis of variance was conducted to evaluate the relationship between degree of racial loading of an exceptionalizing microaggression and the perceived accuracy of a research confederate’s impression of the Asian or Asian American participant. The independent variable, COND, included three levels: control/none, low, and high levels of racial loading. Results of Levene’s homogeneity of variance test indicated no violation of the homogeneity of variance assumption (<span class="math inline">\(F\)</span>[(2,87] = 2.274, <span class="math inline">\(p\)</span> = 0.109 ). Similarly, results of the Shapiro Wilk’s test indicated no violation of the normality assumption <em>W</em> = 0.97413, <em>p</em> = 0.069.</p>
<p>Results indicated a significant effect of COND on accuracy perception $ F(2, 87) = 6.817, p = 0.002, ^2 = .14$. In a series of post-hoc comparisons, there were statistically significant differences between the control and high (<em>p</em> = 0.013) and low and high (<em>p</em> = 0.001) conditions, but not the control and low conditions (<em>p</em> = 0.290). Consequently, it appeared that only the highest degree of racial loading (e.g., “You speak English well for an Asian”) resulted in the decreased perceptions of accuracy of impressions from the confederate. Means and standard deviations are presented in Table 1 and complete ANOVA results are presented in Table 2. Figure 1 provides an illustration of the results.</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="working-the-one-way-anova-in-r.html#cb105-1"></a><span class="kw">library</span>(apaTables)</span>
<span id="cb105-2"><a href="working-the-one-way-anova-in-r.html#cb105-2"></a><span class="kw">apa.aov.table</span> (accBYcond, <span class="dt">table.number =</span> <span class="dv">1</span>, <span class="dt">filename =</span> <span class="st">&quot;Table2.doc&quot;</span>)</span></code></pre></div>
<pre><code>## 
## 
## Table 1 
## 
## ANOVA results using Accurate as the dependent variable
##  
## 
##    Predictor     SS df     MS      F    p partial_eta2 CI_90_partial_eta2
##  (Intercept) 105.68  1 105.68 277.35 .000                                
##         COND   5.20  2   2.60   6.82 .002          .14         [.03, .24]
##        Error  33.15 87   0.38                                            
## 
## Note: Values in square brackets indicate the bounds of the 90% confidence interval for partial eta-squared</code></pre>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="working-the-one-way-anova-in-r.html#cb107-1"></a><span class="kw">plotmeans</span> (<span class="dt">formula =</span> Accurate <span class="op">~</span><span class="st"> </span>COND, <span class="dt">data =</span> accSIM30, <span class="dt">xlab =</span> <span class="st">&quot;Racial Loading Condition&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Accuracy of Confederate&#39;s Impression&quot;</span>, <span class="dt">n.label =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<p><img src="ReCenterPsychStats_files/figure-html/unnamed-chunk-5-1.svg" width="672" /></p>
</div>
<div id="bonus-reel" class="section level2">
<h2><span class="header-section-number">2.10</span> Bonus Reel:</h2>
<div class="figure">
<img src="images/film-strip-1.jpg" id="id" class="class" width="620" height="211" alt="" />
<p class="caption">Image of a filmstrip</p>
</div>
<p>Simulating the ANOVA data from the Tran and Lee <span class="citation">(<a href="#ref-tran_you_2014" role="doc-biblioref">2014</a>)</span> RCT. The data can be simulated for each, one-way ANOVA, separately, but because there is no correlation matrix (showing the relations between all the variables), it is impossible to recreate the entire dataset.</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="working-the-one-way-anova-in-r.html#cb108-1"></a>moreTalk &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">rnorm</span>(<span class="dv">30</span>, <span class="dt">mean=</span><span class="op">-</span>.<span class="dv">82</span>, <span class="dt">sd=</span><span class="fl">0.91</span>), <span class="kw">rnorm</span>(<span class="dv">30</span>, <span class="dt">mean=</span><span class="op">-</span><span class="fl">0.39</span>, <span class="dt">sd =</span> <span class="fl">0.66</span>), <span class="kw">rnorm</span>(<span class="dv">30</span>, <span class="dt">mean =</span> <span class="fl">-0.04</span>, <span class="dt">sd =</span> <span class="fl">0.71</span>))<span class="co">#sample size, M and SD for each group</span></span>
<span id="cb108-2"><a href="working-the-one-way-anova-in-r.html#cb108-2"></a>moreTalk[moreTalk<span class="op">&gt;</span><span class="dv">2</span>]&lt;-<span class="dv">2</span> <span class="co">#set upper bound for DV</span></span>
<span id="cb108-3"><a href="working-the-one-way-anova-in-r.html#cb108-3"></a>moreTalk[moreTalk&lt;-<span class="dv">2</span>]&lt;-<span class="op">-</span><span class="dv">2</span> <span class="co">#set lower bound for DV</span></span>
<span id="cb108-4"><a href="working-the-one-way-anova-in-r.html#cb108-4"></a>ID&lt;-<span class="kw">factor</span>(<span class="kw">seq</span>(<span class="dv">1</span>,<span class="dv">90</span>)) <span class="co">#IDs for participants</span></span>
<span id="cb108-5"><a href="working-the-one-way-anova-in-r.html#cb108-5"></a>COND&lt;-<span class="kw">c</span>(<span class="kw">rep</span>(<span class="st">&quot;High&quot;</span>, <span class="dv">30</span>), <span class="kw">rep</span>(<span class="st">&quot;Low&quot;</span>, <span class="dv">30</span>), <span class="kw">rep</span>(<span class="st">&quot;Control&quot;</span>, <span class="dv">30</span>)) <span class="co">#name factors and identify how many in each group; should be in same order as first row of script</span></span>
<span id="cb108-6"><a href="working-the-one-way-anova-in-r.html#cb108-6"></a>mTalk_sim30 &lt;-<span class="kw">data.frame</span>(ID, COND, moreTalk) <span class="co">#groups the 3 variables into a single df:  ID#, DV, condition</span></span>
<span id="cb108-7"><a href="working-the-one-way-anova-in-r.html#cb108-7"></a></span>
<span id="cb108-8"><a href="working-the-one-way-anova-in-r.html#cb108-8"></a><span class="co">#to write it to an outfile</span></span>
<span id="cb108-9"><a href="working-the-one-way-anova-in-r.html#cb108-9"></a><span class="kw">write.table</span>(mTalk_sim30, <span class="dt">file=</span><span class="st">&quot;newmTalk30.csv&quot;</span>, <span class="dt">sep=</span><span class="st">&quot;,&quot;</span>, <span class="dt">col.names=</span><span class="ot">TRUE</span>, <span class="dt">row.names=</span><span class="ot">FALSE</span>)</span></code></pre></div>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="working-the-one-way-anova-in-r.html#cb109-1"></a><span class="kw">sessionInfo</span>()</span></code></pre></div>
<pre><code>## R version 4.0.3 (2020-10-10)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 10 x64 (build 18362)
## 
## Matrix products: default
## 
## locale:
## [1] LC_COLLATE=English_United States.1252 
## [2] LC_CTYPE=English_United States.1252   
## [3] LC_MONETARY=English_United States.1252
## [4] LC_NUMERIC=C                          
## [5] LC_TIME=English_United States.1252    
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
##  [1] apaTables_2.0.8 pwr_1.3-0       lsr_0.5         car_3.0-10     
##  [5] carData_3.0-4   psych_2.0.12    forcats_0.5.0   stringr_1.4.0  
##  [9] dplyr_1.0.2     purrr_0.3.4     readr_1.4.0     tidyr_1.1.2    
## [13] tibble_3.0.4    ggplot2_3.3.3   tidyverse_1.3.0 gdtools_0.2.2  
## [17] gplots_3.1.1   
## 
## loaded via a namespace (and not attached):
##  [1] httr_1.4.2         jsonlite_1.7.2     tmvnsim_1.0-2      modelr_0.1.8      
##  [5] gtools_3.8.2       assertthat_0.2.1   highr_0.8          cellranger_1.1.0  
##  [9] yaml_2.2.1         pillar_1.4.7       backports_1.2.0    lattice_0.20-41   
## [13] glue_1.4.2         digest_0.6.27      rvest_0.3.6        colorspace_2.0-0  
## [17] htmltools_0.5.0    pkgconfig_2.0.3    broom_0.7.3        haven_2.3.1       
## [21] bookdown_0.21      scales_1.1.1       svglite_1.2.3.2    openxlsx_4.2.3    
## [25] rio_0.5.16         generics_0.1.0     ellipsis_0.3.1     withr_2.3.0       
## [29] cli_2.2.0          mnormt_2.0.2       magrittr_2.0.1     crayon_1.3.4      
## [33] readxl_1.3.1       evaluate_0.14      fs_1.5.0           fansi_0.4.1       
## [37] nlme_3.1-151       foreign_0.8-81     xml2_1.3.2         MBESS_4.8.0       
## [41] tools_4.0.2        data.table_1.13.4  hms_0.5.3          lifecycle_0.2.0   
## [45] munsell_0.5.0      reprex_0.3.0       zip_2.1.1          compiler_4.0.2    
## [49] caTools_1.18.0     systemfonts_0.3.2  rlang_0.4.9        grid_4.0.2        
## [53] rstudioapi_0.13    bitops_1.0-6       rmarkdown_2.6      gtable_0.3.0      
## [57] abind_1.4-5        DBI_1.1.0          curl_4.3           R6_2.5.0          
## [61] lubridate_1.7.9.2  knitr_1.30         KernSmooth_2.23-18 stringi_1.5.3     
## [65] parallel_4.0.2     Rcpp_1.0.5         vctrs_0.3.6        dbplyr_2.0.0      
## [69] tidyselect_1.1.0   xfun_0.19</code></pre>
</div>
<div id="references" class="section level2">
<h2><span class="header-section-number">2.11</span> References</h2>

<div id="refs" class="references">
<div>
<p>Crump, M. J. C. (2018). <em>Programming for Psychologists: Data Creation and Analysis</em>. <a href="https://crumplab.github.io/programmingforpsych/index.html">https://crumplab.github.io/programmingforpsych/index.html</a></p>
</div>
<div>
<p>Field, A. P. (2012). <em>Discovering statistics using R</em>. Sage.</p>
</div>
<div>
<p>Green, S. B., &amp; Salkind, N. J. (2014). <em>Using SPSS for Windows and Macintosh: Analyzing and understanding data</em> (Seventh edition.). Pearson.</p>
</div>
<div>
<p>Kline, R. B. (2016). <em>Principles and practice of structural equation modeling</em> (4th ed.). Guilford Publications. <a href="http://ebookcentral.proquest.com/lib/spu/detail.action?docID=4000663">http://ebookcentral.proquest.com/lib/spu/detail.action?docID=4000663</a></p>
</div>
<div>
<p>Mallinckrodt, B., Miles, J. R., &amp; Levy, J. J. (2014). The scientist-practitioner-advocate model: Addressing contemporary training needs for social justice advocacy. <em>Training and Education in Professional Psychology</em>, <em>8</em>(4), 303–311. <a href="https://doi.org/10.1037/tep0000045">https://doi.org/10.1037/tep0000045</a></p>
</div>
<div>
<p>Navarro, D. (2020a). <em>Book: Learning Statistics with R - A tutorial for Psychology Students and other Beginners</em>. Open Education Resource (OER) LibreTexts Project. <a href="https://stats.libretexts.org/Bookshelves/Applied_Statistics/Book%3A_Learning_Statistics_with_R_-_A_tutorial_for_Psychology_Students_and_other_Beginners_(Navarro)">https://stats.libretexts.org/Bookshelves/Applied_Statistics/Book%3A_Learning_Statistics_with_R_-_A_tutorial_for_Psychology_Students_and_other_Beginners_(Navarro)</a></p>
</div>
<div>
<p>Navarro, D. (2020b). Chapter 14: Comparing Several Means (One-Way ANOVA). In <em>Book: Learning Statistics with R - A tutorial for Psychology Students and other Beginners</em>. Open Education Resource (OER) LibreTexts Project. <a href="https://stats.libretexts.org/Bookshelves/Applied_Statistics/Book%3A_Learning_Statistics_with_R_-_A_tutorial_for_Psychology_Students_and_other_Beginners_(Navarro)">https://stats.libretexts.org/Bookshelves/Applied_Statistics/Book%3A_Learning_Statistics_with_R_-_A_tutorial_for_Psychology_Students_and_other_Beginners_(Navarro)</a></p>
</div>
<div>
<p>Tran, A. G. T. T., &amp; Lee, R. M. (2014). You speak English well! Asian Americans’ reactions to an exceptionalizing stereotype. <em>Journal of Counseling Psychology</em>, <em>61</em>(3), 484–490. <a href="https://doi.org/10.1037/cou0000034">https://doi.org/10.1037/cou0000034</a></p>
</div>
</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-green_using_2014">
<p>Green, S. B., &amp; Salkind, N. J. (2014). <em>Using SPSS for Windows and Macintosh: Analyzing and understanding data</em> (Seventh edition.). Pearson.</p>
</div>
<div id="ref-kline_principles_2016">
<p>Kline, R. B. (2016). <em>Principles and practice of structural equation modeling</em> (4th ed.). Guilford Publications. <a href="http://ebookcentral.proquest.com/lib/spu/detail.action?docID=4000663">http://ebookcentral.proquest.com/lib/spu/detail.action?docID=4000663</a></p>
</div>
<div id="ref-navarro_book_2020">
<p>Navarro, D. (2020a). <em>Book: Learning Statistics with R - A tutorial for Psychology Students and other Beginners</em>. Open Education Resource (OER) LibreTexts Project. <a href="https://stats.libretexts.org/Bookshelves/Applied_Statistics/Book%3A_Learning_Statistics_with_R_-_A_tutorial_for_Psychology_Students_and_other_Beginners_(Navarro)">https://stats.libretexts.org/Bookshelves/Applied_Statistics/Book%3A_Learning_Statistics_with_R_-_A_tutorial_for_Psychology_Students_and_other_Beginners_(Navarro)</a></p>
</div>
<div id="ref-tran_you_2014">
<p>Tran, A. G. T. T., &amp; Lee, R. M. (2014). You speak English well! Asian Americans’ reactions to an exceptionalizing stereotype. <em>Journal of Counseling Psychology</em>, <em>61</em>(3), 484–490. <a href="https://doi.org/10.1037/cou0000034">https://doi.org/10.1037/cou0000034</a></p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="oneway.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/ontheline/otl-bookdown/blob/master/02-OnewayANOVA.Rmd",
"text": null
},
"download": ["ReCenterPsychStats.pdf"],
"toc": {
"collapse": "section",
"scroll_highlight": true
},
"search": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
